###########
# BUILDER #
###########

# pull official base image
FROM python:3.14.7-slim-bookworm@sha256:23c59390fc717bf09f9336908199a0ae75d9c4264bf296123f94ad772fea3b52 AS builder

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV APP_HOME=/home/app/web
ENV UV_PROJECT_ENVIRONMENT=$APP_HOME/.venv
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

# install uv
COPY --from=ghcr.io/astral-sh/uv:0.11.14@sha256:1025398289b62de8269e70c45b91ffa37c373f38118d7da036fb8bb8efc85d97 /uv /uvx /bin/

# install system dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl libpq-dev git build-essential
RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
    apt-get install -y nodejs

COPY . .

# install python dependencies
RUN uv sync --frozen --no-dev --group prod
# install js dependencies
RUN npm install
# build js
RUN npm run build:prod

#########
# FINAL #
#########

# pull official base image
FROM python:3.14.7-slim-bookworm@sha256:23c59390fc717bf09f9336908199a0ae75d9c4264bf296123f94ad772fea3b52

# create directory for the app user
RUN mkdir -p /home/app

# create the app user
RUN addgroup --system app && adduser --system --group app

# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
RUN mkdir $APP_HOME/mediafiles
WORKDIR $APP_HOME

# install dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends netcat-traditional libpq5 gettext curl

# copy venv from builder
COPY --from=builder $APP_HOME/.venv $APP_HOME/.venv
ENV PATH="$APP_HOME/.venv/bin:$PATH"

# copy entrypoint.prod.sh
COPY ./entrypoint.prod.sh .
RUN sed -i 's/\r$//g'  $APP_HOME/entrypoint.prod.sh
RUN chmod +x  $APP_HOME/entrypoint.prod.sh

# copy project
COPY . $APP_HOME
# copy webpack build files
COPY --from=builder $APP_HOME/wine_cellar/static wine_cellar/static
COPY --from=builder $APP_HOME/webpack-stats.json webpack-stats.json

# chown all the files to the app user
RUN chown -R app:app $HOME

# change to the app user
USER app

# run entrypoint.prod.sh
ENTRYPOINT ["/home/app/web/entrypoint.prod.sh"]
