services:
  web:
    image: ghcr.io/the-broke-sommeliers/wine-cellar-web:v0.0.10
    command: gunicorn wine_cellar.conf.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    environment:
      - CONTAINER_ROLE=web
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:8085:80
    volumes:
      - ./caddy:/etc/caddy/
      - static_volume:/srv/static
      - media_volume:/srv/media
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
  redis:
    image: redis:alpine
  celery:
    image: ghcr.io/the-broke-sommeliers/wine-cellar-web:v0.0.10
    command: celery -A wine_cellar.conf worker -l info
    env_file:
      - ./.env.prod
    depends_on:
      web:
        condition: service_healthy
      redis:
        condition: service_started
  celery-beat:
    image: ghcr.io/the-broke-sommeliers/wine-cellar-web:v0.0.10
    command: celery -A wine_cellar.conf beat -l info
    env_file:
      - ./.env.prod
    depends_on:
      web:
        condition: service_healthy
      redis:
        condition: service_started
volumes:
  postgres_data:
  static_volume:
  media_volume:
  caddy_data:
  caddy_config:
