site_name: Wine Cellar Documentation
nav:
  - Home: README.md
  - Getting Started: deployment.md
  - Development:
    - Setup: setup.md
    - Testing: testing.md
  - Wine: wine.md
  - Storage: storage.md

theme:
  name: material
  logo: logo.svg
  favicon: logo.svg

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
