# Generated by Django 5.0.1 on 2024-02-18 08:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FoodPairing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Grape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_id", models.BigIntegerField(null=True)),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Vintage",
            fields=[
                (
                    "name",
                    models.PositiveIntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2024),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wine_id", models.BigIntegerField(null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "wine_type",
                    models.CharField(
                        choices=[
                            ("WH", "White"),
                            ("RE", "Red"),
                            ("RO", "Rose"),
                            ("SP", "Sparkling"),
                            ("DE", "Dessert"),
                            ("FO", "Fortified"),
                        ],
                        max_length=2,
                    ),
                ),
                ("elaborate", models.CharField(blank=True, max_length=100, null=True)),
                ("body", models.CharField(blank=True, max_length=100)),
                ("acidity", models.CharField(blank=True, max_length=100)),
                ("abv", models.FloatField()),
                ("capacity", models.FloatField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, max_length=250)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Winery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winery_id", models.BigIntegerField(null=True)),
                ("name", models.CharField(max_length=100)),
                ("website", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="classification",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique classification"
            ),
        ),
        migrations.AddConstraint(
            model_name="foodpairing",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique food pairing"
            ),
        ),
        migrations.AddConstraint(
            model_name="grape",
            constraint=models.UniqueConstraint(fields=("name",), name="unique grape"),
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.UniqueConstraint(
                fields=("name", "country"), name="unique region"
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="classification",
            field=models.ManyToManyField(to="wine.classification"),
        ),
        migrations.AddField(
            model_name="wine",
            name="food_pairings",
            field=models.ManyToManyField(to="wine.foodpairing"),
        ),
        migrations.AddField(
            model_name="wine",
            name="grapes",
            field=models.ManyToManyField(to="wine.grape"),
        ),
        migrations.AddField(
            model_name="wine",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wine.region",
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="vintage",
            field=models.ManyToManyField(to="wine.vintage"),
        ),
        migrations.AddField(
            model_name="winery",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wine.region",
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="winery",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wine.winery",
            ),
        ),
        migrations.AddConstraint(
            model_name="winery",
            constraint=models.UniqueConstraint(
                fields=("name", "region"), name="unique winery"
            ),
        ),
        migrations.AddConstraint(
            model_name="wine",
            constraint=models.UniqueConstraint(
                fields=("name", "wine_type", "abv", "capacity", "winery"),
                name="unique wine",
            ),
        ),
    ]
