# Generated by Django 5.0.1 on 2024-01-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wine',
            constraint=models.UniqueConstraint(fields=('name', 'wine_type', 'abv', 'capacity', 'vintage'), name='unique appversion'),
        ),
    ]
