# Generated by Django 5.0.1 on 2024-10-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(fields=("name",), name="unique source"),
        ),
        migrations.AddField(
            model_name="wine",
            name="source",
            field=models.ManyToManyField(to="wine.source"),
        ),
    ]
