# Generated by Django 5.0.1 on 2024-02-24 17:04

import django.db.models.deletion
from django.db import migrations, models

import wine_cellar.apps.wine.models


class Migration(migrations.Migration):
    dependencies = [
        ("wine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WineImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=wine_cellar.apps.wine.models.user_directory_path
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wine.wine"
                    ),
                ),
            ],
        ),
    ]
