# Generated by Django 5.0.1 on 2024-02-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="capacity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
