# Generated by Django 5.0.1 on 2024-02-01 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine", "0002_alter_wine_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="rating",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
