# Generated by Django 5.0.1 on 2024-01-28 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_wine_unique_appversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='wine.wine'),
        ),
    ]
