# Generated by Django 5.0.1 on 2024-10-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine", "0003_remove_wine_region_alter_winery_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="abv",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
