# Generated by Django 5.1.2 on 2025-01-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0003_alter_wine_vintage"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="barcode",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
