# Generated by Django 5.0.1 on 2024-02-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine", "0003_alter_wine_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="wine_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
