# Generated by Django 5.0.1 on 2024-02-24 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine", "0004_wine_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
