# Generated by Django 5.0.1 on 2024-02-01 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine", "0004_wine_wine_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="vintage",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
        ),
    ]
