# Generated by Django 5.1.6 on 2025-02-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0004_wine_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodpairing",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Food"),
        ),
        migrations.AlterField(
            model_name="grape",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Grape"),
        ),
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.FloatField(verbose_name="Size"),
        ),
    ]
