# Generated by Django 5.2.3 on 2025-06-27 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0005_alter_foodpairing_name_alter_grape_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="grape",
            name="unique grape",
        ),
        migrations.AddConstraint(
            model_name="grape",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique grape"
            ),
        ),
        migrations.AddConstraint(
            model_name="size",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique size"
            ),
        ),
    ]
