# Generated by Django 5.0.1 on 2024-02-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wine", "0005_alter_wine_vintage"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="region_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="winery",
            name="winery_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
