# Generated by Django 5.2.3 on 2025-06-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0006_remove_grape_unique_grape_grape_unique_grape_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="drink_by",
            field=models.DateField(blank=True, null=True),
        ),
    ]
