# Generated by Django 5.2.3 on 2025-06-28 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0007_wine_drink_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wine",
            name="unique wine",
        ),
        migrations.AddConstraint(
            model_name="wine",
            constraint=models.UniqueConstraint(
                fields=(
                    "name",
                    "wine_type",
                    "abv",
                    "size",
                    "vintage",
                    "country",
                    "user",
                ),
                name="unique wine",
            ),
        ),
    ]
