# Generated by Django 5.2.3 on 2025-06-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0008_remove_wine_unique_wine_wine_unique_wine"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
