# Generated by Django 5.2.6 on 2025-09-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0009_wine_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wine",
            name="stock",
        ),
    ]
