# Generated by Django 5.2.7 on 2025-10-14 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0010_remove_wine_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Classification",
            new_name="Attribute",
        ),
        migrations.RemoveConstraint(
            model_name="attribute",
            name="unique classification",
        ),
        migrations.RenameField(
            model_name="wine",
            old_name="classification",
            new_name="attributes",
        ),
        migrations.AddConstraint(
            model_name="attribute",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique attributes"
            ),
        ),
    ]
