# Generated by Django 5.2.7 on 2025-10-15 17:40

from django.db import migrations, models

import wine_cellar.apps.wine.utils


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0011_rename_classification_attribute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wineimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=wine_cellar.apps.wine.utils.user_directory_path,
            ),
        ),
    ]
