# Generated by Django 5.2.7 on 2025-10-15 17:33

from django.db import migrations

from wine_cellar.apps.wine.utils import make_thumbnail


def create_thumbnails(apps, schema_editor):
    WineImage = apps.get_model("wine", "WineImage")
    for image in WineImage.objects.all():
        if image.image and not image.thumbnail:
            thumb_rel_path = make_thumbnail(image)
            image.thumbnail.name = thumb_rel_path
            image.save(update_fields=["thumbnail"])


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0012_wineimage_thumbnail"),
    ]

    operations = [
        migrations.RunPython(create_thumbnails, migrations.RunPython.noop),
    ]
