# Generated by Django 5.2.7 on 2025-10-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0013_create_thumbnails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="wine_type",
            field=models.CharField(
                choices=[
                    ("WH", "White"),
                    ("RE", "Red"),
                    ("RO", "Rose"),
                    ("SP", "Sparkling"),
                    ("DE", "Dessert"),
                    ("FO", "Fortified"),
                    ("OR", "Orange"),
                ],
                max_length=2,
            ),
        ),
    ]
