# Generated by Django 5.2.8 on 2025-12-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0014_alter_wine_wine_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="wineimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("FR", "Front"),
                    ("BA", "Back"),
                    ("LF", "Label Front"),
                    ("LB", "Label Back"),
                ],
                default="FR",
                max_length=3,
            ),
        ),
    ]
