# Generated by Django 5.2.10 on 2026-01-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0015_wineimage_image_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="wine",
            name="location",
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
    ]
