# Generated by Django 5.2.11 on 2026-02-13 12:07

from django.db import connection, migrations

CELERY_BEAT_TABLES = [
    "django_celery_beat_periodictask",
    "django_celery_beat_solarschedule",
    "django_celery_beat_intervalschedule",
    "django_celery_beat_clockedschedule",
    "django_celery_beat_crontabschedule",
    "django_celery_beat_periodictasks",
]


def drop_celery_beat_tables(apps, schema_editor):
    with connection.cursor() as cursor:
        for table in CELERY_BEAT_TABLES:
            cursor.execute(f'DROP TABLE IF EXISTS "{table}"')


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0017_appellation_wine_appellation_region_wine_region_and_more"),
    ]

    operations = [
        migrations.RunPython(drop_celery_beat_tables),
    ]
