# Generated by Django 6.1.1 on 2026-09-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wine", "0021_cleanup_wine_vintage_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wine",
            name="wine_type",
            field=models.CharField(
                choices=[
                    ("WH", "White"),
                    ("RE", "Red"),
                    ("RO", "Rose"),
                    ("SP", "Sparkling"),
                    ("DE", "Dessert"),
                    ("FO", "Fortified"),
                    ("OR", "Orange"),
                    ("FW", "Federweisser"),
                    ("FR", "Federroter"),
                ],
                max_length=2,
            ),
        ),
    ]
