"""
Django settings for wine_cellar project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from django.utils.csp import CSP
from django.utils.translation import gettext_lazy as _

from wine_cellar import __version__

# Build paths inside the project like this: BASE_DIR / 'subdir'.
ROOT_DIR = Path(__file__).resolve().parent.parent.parent
BASE_DIR = Path(__file__).resolve().parent.parent
VERSION = __version__

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-9_c29b95eghgc@yx6lyuiz3*h#oy7*zh8*vb36d1cwe)b4%v0d")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True").lower() in ("true", "1", "yes")


ALLOWED_HOSTS = []

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.openid_connect",
    "widget_tweaks",
    "webpack_loader",
    "wine_cellar.apps.wine",
    "wine_cellar.apps.user",
    "wine_cellar.apps.storage",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "wine_cellar.conf.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wine_cellar.conf.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "db.sqlite3",
        "TEST": {
            "NAME": "test_db.sqlite3",
        },
    }
}

# `wine_prefill` backs the short-lived AI-scan/barcode wine-add prefill data
# (see wine_cellar.apps.wine.views); overridden to a Redis backend in
# docker_settings.py/docker_dev_settings.py, local-memory here for dev/tests.
CACHES = {
    "default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"},
    "wine_prefill": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"},
}

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/Berlin"

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [ROOT_DIR / "locale"]

LANGUAGES = [
    ("de-DE", _("German")),
    ("fr-FR", _("French")),
    ("sv-SE", _("Swedish")),
    ("en-gb", _("British English")),
]

# LOCALE_PATHS = [BASE_DIR / "locale"]

CURRENCIES = [
    ("EUR", _("Euro")),
    ("USD", _("Dollar")),
    ("GBP", _("Pound Sterling")),
]

CURRENCY_SYMBOLS = {"EUR": "€", "USD": "$", "GBP": "£"}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

WEBPACK_LOADER = {
    "DEFAULT": {
        "BUNDLE_DIR_NAME": "",
        "CACHE": not DEBUG,
        "STATS_FILE": ROOT_DIR / "webpack-stats.json",
        "IGNORE": [r".+\.hot-update\.js", r".+\.map", r".+\.LICENSE\.txt"],
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MEDIA_ROOT = "media/"
MEDIA_URL = "media/"

MAP_BASEURL = "https://tiles.openfreemap.org/styles/liberty"

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
SITE_URL = "http://127.0.0.1:8003"
ACCOUNT_ADAPTER = (
    "wine_cellar.apps.user.signup_adapter.ConfigurableSignupAccountAdapter"
)

ENABLE_SIGNUPS = False
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_SIGNUP_FIELDS = ["email", "username*", "password1*", "password2*"]

SECURE_CSP = {
    "default-src": [CSP.SELF],
    "frame-ancestors": [CSP.SELF],
    "form-action": [CSP.SELF],
    "base-uri": [CSP.NONE],
    "connect-src": [CSP.SELF, "https://tiles.openfreemap.org/"],
    "worker-src": [CSP.SELF, "blob:"],
    "img-src": [CSP.SELF, "data:"],
    "script-src": [CSP.SELF, CSP.WASM_UNSAFE_EVAL],
}
