# Generated by Django 5.2.6 on 2025-09-26 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wine", "0009_wine_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Storage Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Storage Description"
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="Location")),
                (
                    "rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Number of Rows"
                    ),
                ),
                (
                    "columns",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Number of Columns"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StorageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("row", models.PositiveIntegerField(blank=True, null=True)),
                ("column", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="storage.storage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wine.wine"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
