# Generated by Django 5.2.7 on 2025-10-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_add_default_shelf"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageitem",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
