# Generated by Django 5.2.9 on 2025-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_storageitem_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
