# Generated by Django 6.0.5 on 2026-06-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_storageitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageitem",
            name="drink_by",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="storageitem",
            name="opened",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="storageitem",
            name="opened_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
