# Generated by Django 6.0.7 on 2026-08-08 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0005_storageitem_drink_by_storageitem_opened_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="column_labels_enabled",
            field=models.BooleanField(default=True, verbose_name="Show Column Labels"),
        ),
        migrations.AddField(
            model_name="storage",
            name="row_labels_enabled",
            field=models.BooleanField(default=True, verbose_name="Show Row Labels"),
        ),
        migrations.AddField(
            model_name="storage",
            name="swap_axes",
            field=models.BooleanField(default=False, verbose_name="Show Columns First"),
        ),
        migrations.CreateModel(
            name="StorageLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "axis",
                    models.CharField(
                        choices=[("row", "Row"), ("column", "Column")], max_length=6
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=100)),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="storage.storage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("storage", "axis", "index")},
            },
        ),
    ]
