# Generated by Django 6.0.7 on 2026-08-10 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0006_storage_column_labels_enabled_and_more"),
        ("wine", "0018_remove_django_celery_beat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageItemEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("wine_name", models.CharField(max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("added", "Added"),
                            ("opened", "Opened"),
                            ("consumed", "Consumed"),
                            ("removed", "Removed"),
                            ("undo_open", "Opening Undone"),
                            ("wine_added", "Wine Added"),
                            ("wine_removed", "Wine Removed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "storage_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="storage.storageitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="wine.wine",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
