# Generated by Django 6.0.7 on 2026-08-10 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0008_backfill_storageitemevent"),
        ("wine", "0018_remove_django_celery_beat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="storageitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("column__isnull", False),
                    ("deleted", False),
                    ("row__isnull", False),
                ),
                fields=("storage", "row", "column"),
                name="unique_active_slot_per_storage",
            ),
        ),
    ]
