# Generated by Django 6.1 on 2026-08-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0012_storageitemevent_vintage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storageitemevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("added", "Added"),
                    ("opened", "Opened"),
                    ("consumed", "Consumed"),
                    ("removed", "Removed"),
                    ("undo_open", "Opening Undone"),
                    ("wine_added", "Wine Added"),
                    ("wine_removed", "Wine Removed"),
                    ("vintage_removed", "Vintage Removed"),
                ],
                max_length=16,
            ),
        ),
    ]
