# Generated by Django 5.2.3 on 2025-06-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "Euro"), ("USD", "Dollar"), ("GBP", "Pound Sterling")],
                default="EUR",
                max_length=3,
            ),
        ),
    ]
