# Generated by Django 5.2.3 on 2025-06-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_usersettings_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="notifications",
            field=models.BooleanField(default=True),
        ),
    ]
