# Generated by Django 5.2.11 on 2026-02-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_usersettings_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="language",
            field=models.CharField(
                choices=[
                    ("de-DE", "German"),
                    ("fr-FR", "French"),
                    ("en-gb", "British English"),
                ],
                default="en-gb",
                max_length=7,
            ),
        ),
    ]
