# Generated by Django 6.0.7 on 2026-08-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_usersettings_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="language",
            field=models.CharField(
                choices=[
                    ("de-DE", "German"),
                    ("fr-FR", "French"),
                    ("sv-SE", "Swedish"),
                    ("en-gb", "British English"),
                ],
                default="en-gb",
                max_length=7,
            ),
        ),
    ]
