# Generated by Django 6.1 on 2026-08-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_usersettings_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="last_seen_whats_new_version",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
