import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8003/accounts/login/?next=/');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('admin');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('password');
  await page.getByRole('textbox', { name: 'Password' }).press('Tab');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Add Wine' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('Vino Del Blanco');
  await page.getByRole('textbox', { name: 'Name' }).press('Tab');
  await page.getByLabel('Wine type').selectOption('DE');
  await page.getByLabel('Wine type').press('Tab');
  await page.getByLabel('Country').selectOption('ES');
  await page.getByLabel('Country').press('Tab');
  await page.getByLabel('Size').press('ArrowDown');
  await page.getByLabel('Size').press('ArrowDown');
  await page.getByLabel('Size').press('ArrowDown');
  await page.getByLabel('Size').press('ArrowDown');
  await page.getByLabel('Size').press('ArrowDown');
  await page.getByLabel('Size').press('ArrowUp');
  await page.getByLabel('Size').press('Enter');
  await page.getByLabel('Size').press('Tab');
  await page.getByRole('button', { name: 'Continue' }).press('Tab');
  await page.getByRole('link', { name: 'Github (opens in new tab)' }).press('Shift+Tab');
  await page.getByRole('button', { name: 'Continue' }).press('Enter');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('Grapes (Optional)').selectOption('2');
  await page.getByText('Grapes (Optional) Select or').click();
  await page.getByLabel('Grapes (Optional)').press('Tab');
  await page.getByRole('spinbutton', { name: 'Vintage (Optional)' }).press('ArrowDown');
  await page.getByRole('spinbutton', { name: 'Vintage (Optional)' }).fill('1999');
  await page.getByRole('spinbutton', { name: 'Vintage (Optional)' }).press('Tab');
  await page.getByRole('spinbutton', { name: 'Abv (Optional)' }).fill('12.5');
  await page.getByRole('spinbutton', { name: 'Abv (Optional)' }).press('Tab');
  await page.getByLabel('Sweetness (Optional)').selectOption('SD');
  await page.getByLabel('Sweetness (Optional)').press('Tab');
  await page.getByRole('button', { name: 'Continue' }).press('Enter');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
});